# bridge_config.yaml
# Configuración del Bridge MQTT-OPCUA

# Configuración MQTT
mqtt:
  broker_host: "localhost"
  broker_port: 1883
  client_id: "mqtt_opcua_bridge_01"
  username: null  # Opcional: usuario MQTT
  password: null  # Opcional: contraseña MQTT
  keep_alive: 60
  qos: 1
  tls_enabled: false
  ca_cert: null
  client_cert: null
  client_key: null

# Configuración OPC-UA
opcua:
  endpoint: "opc.tcp://0.0.0.0:4840/bridge/server/"
  server_name: "MQTT-OPCUA Bridge Server"
  namespace: "http://mqtt-opcua-bridge.com"
  security_policy: "NoSecurity"  # Opciones: NoSecurity, Basic256Sha256, Basic128Rsa15
  certificate: null
  private_key: null
  allow_anonymous: true

# Mapeo entre topics MQTT y nodos OPC-UA
mappings:
  # Sensor de temperatura
  - mqtt_topic: "sensores/temperatura/sala"
    opcua_node_id: "ns=2;s=Temperature.Room"
    data_type: "Float"
    direction: "mqtt_to_opcua"  # mqtt_to_opcua, opcua_to_mqtt, bidirectional
    
  # Sensor de humedad
  - mqtt_topic: "sensores/humedad/sala"
    opcua_node_id: "ns=2;s=Humidity.Room"
    data_type: "Float"
    direction: "mqtt_to_opcua"
    
  # Control de luz
  - mqtt_topic: "actuadores/luz/sala"
    opcua_node_id: "ns=2;s=Light.Room"
    data_type: "Boolean"
    direction: "bidirectional"
    
  # Setpoint de temperatura
  - mqtt_topic: "control/setpoint/temperatura"
    opcua_node_id: "ns=2;s=Setpoint.Temperature"
    data_type: "Float"
    direction: "opcua_to_mqtt"
    
  # Estado del sistema
  - mqtt_topic: "sistema/estado"
    opcua_node_id: "ns=2;s=System.Status"
    data_type: "String"
    direction: "bidirectional"
    
  # Datos JSON complejos
  - mqtt_topic: "datos/json/dispositivo1"
    opcua_node_id: "ns=2;s=Device1.Data"
    data_type: "JSON"
    direction: "bidirectional"
    
  # Timestamp
  - mqtt_topic: "sistema/ultima_actualizacion"
    opcua_node_id: "ns=2;s=System.LastUpdate"
    data_type: "DateTime"
    direction: "mqtt_to_opcua"
    
  # Contador de producción
  - mqtt_topic: "produccion/contador"
    opcua_node_id: "ns=2;s=Production.Counter"
    data_type: "Int32"
    direction: "opcua_to_mqtt"
    
  # Alarma del sistema
  - mqtt_topic: "alarmas/activa"
    opcua_node_id: "ns=2;s=Alarm.Active"
    data_type: "Boolean"
    direction: "bidirectional"
    
  # Valor de proceso
  - mqtt_topic: "proceso/valor/pv1"
    opcua_node_id: "ns=2;s=Process.PV1"
    data_type: "Double"
    direction: "mqtt_to_opcua"

# Configuración del buffer persistente optimizada para Raspberry Pi 2
buffer:
  enabled: true
  db_path: "buffer.db"
  max_size: 2000
  ttl_minutes: 30
  cleanup_interval: 120
  worker_threads: 1
  retry_max_attempts: 3
  retry_backoff_seconds: 5
  wal_enabled: true

# Configuración de optimización (modo conservador)
optimization:
  enabled: true
  profile: "resource_constrained"
  auto_adjust: false
  check_interval: 600

# Monitoreo deshabilitado para ahorrar recursos
monitoring:
  enabled: false
  export_metrics: false
  alerts_enabled: false

# Logging
logging:
  level: "INFO"
  file_enabled: true
  file_path: "logs/bridge.log"
  console_enabled: true
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

sap:
  enabled: false
  endpoint: "https://sap.example.com/odata/bridge"
  timeout: 15
  poll_interval: 20
  auth:
    type: "basic"
    username: null
    password: null
  mappings:
    - mapping_id: "sap_production_orders"
      mqtt_topic: "sap/ordenes"
      opcua_node_id: null
      direction: "bidirectional"
      priority: "high"
      resource_path: "ProductionOrders"
      outbound:
        resource_path: "ProductionOrders"
        transform: null
      inbound:
        destination: "mqtt"
        target: "sap/ordenes"
        data_type: "JSON"
        transform: null
      retry:
        max_attempts: 5
        backoff_seconds: 5
      query_params:
        $top: 10
        status: "OPEN"

# Compatibilidad con configuraciones anteriores
log_level: "INFO"
reconnect_interval: 5
buffer_size: 2000
persistence_enabled: true
persistence_file: "buffer.db"
message_ttl_minutes: 30
cleanup_interval: 120
worker_threads: 1
